language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"

install:
 - sudo apt-get update -qq
 - sudo apt-get install -y python-pip arduino
 - wget http://ftp.us.debian.org/debian/pool/main/a/arduino/arduino-core_1.0.5+dfsg2-4_all.deb
 - sudo dpkg -i arduino-core_1.0.5+dfsg2-4_all.deb
 - pip install coveralls 
 - pip install -r requirements-test.txt
 - pip install .

script:  
 - cd tests && nosetests -v --with-coverage --cover-package=confduino  
 
after_success:
 - coveralls
